### ISSUE TITLE
Fix `undefined` error when clicking cancel button while receiving

### ISSUE THREAD

**Issue by dlguswo333** [dlguswo333/tishare-desktop#23]

**Comment by dlguswo333** [comment]
Error message clicking cancel button while sending
```text
sendRequest: connected to 192.168.0.38
sendRequest: connected to 192.168.0.38
(node:12448) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading '1')
    at Sender.deleteJob [as _deleteCallback] (C:\Users\dlguswo\workspace\tishare-desktop\src\back\Client.js:267:18)
    at Socket.<anonymous> (C:\Users\dlguswo\workspace\tishare-desktop\src\back\Sender.js:192:14)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:12448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by dlguswo333** [comment]
The problem originates from that when creating new instances of `Sender` or `Receiver`,
`Server` or `Client` hands over `deleteJob` method of its own, but since it was not bound to `Server` or `Client`,
`this` in `deleteJob` method was set to `Sender` or `Receiver`, which results in the error.
